// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class HelloWorldTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "E:/Selenium/Drivers/chromedriver.exe");//Added manually. Not always neccessary. In my case it was neccessary beacuse of on error.
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void helloWorldTest() {
    driver.get("https://www.google.co.il/");
    driver.manage().window().setSize(new Dimension(1404, 988));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("Hello World!");
    {
      String value = driver.findElement(By.name("q")).getAttribute("value");
      assertThat(value, is("Hello World!"));
    }
  }
}
